---

name: CI
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]


jobs:

  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        target:
          - aarch64-linux-musl
          - arm-linux-musleabi
          - arm-linux-musleabihf
          - i686-linux-musl
          - riscv64-linux-musl
          - x86_64-linux-musl
          - x86_64-linux-muslx32

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'richfelker/musl-cross-make.git'
          ref: 'master'

      - name: Configure caching
        uses: actions/cache@v2
        # Caching disabled on macos due to https://github.com/actions/cache/issues/403
        if: ${{ matrix.os != 'macos-latest' }}
        with:
          key: ${{ matrix.os }}-${{ matrix.target }}
          path: |
            Sources/
            output/
            binutils-*/
            gcc-*/
            musl-*/
            gmp-*/
            mpc-*/
            mpfr-*/
            build-*/
            linux-*/
            isl-*/
            build/

        # musl-cross-make seems to require sha1sum, should use shasum on macos?
      - name: Install deps (macos)
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install md5sha1sum

        # wget not included in windows-bash? hopefully choco version works
      - name: Install deps (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: choco install wget --no-progress 

      - name: Build MUSL
        shell: bash
        run: TARGET=${{ matrix.target }} make -j

      - name: Package outputs
        run: tar -cf musl-${{ matrix.os }}-${{ matrix.target }}.tgz -C build/local ${{matrix.target}}

      - name: Upload CI artifacts
        uses: actions/upload-artifact@v1
        with:
          name: musl-${{ matrix.os }}-${{ matrix.target }}.tgz
          path: musl-${{ matrix.os }}-${{ matrix.target }}.tgz

      - name: Upload utility binary to release
        # Only publish releases on version tags
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: musl-${{ matrix.os }}-${{ matrix.target }}.tgz
          asset_name: sx128x-util-${{ matrix.target }}.tgz
          tag: ${{ github.ref }}
          overwrite: true

